[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ffpack"
version = "0.0.0"
authors = [
  { name="Dongping Zhu" },
]
description = "Fatigue and fracture package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

[project.urls]
"Homepage" = "https://github.com/dpzhuX/ffpack"
"Bug Tracker" = "https://github.com/dpzhuX/ffpack/issues"
